# Generated by Django 4.0.5 on 2022-07-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app_teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='author',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
