# Generated by Django 4.0.5 on 2022-07-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app_teacher', '0004_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option1',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option2',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option3',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option4',
            new_name='D',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionTitle',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quizId',
            new_name='quiz_id',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=200),
        ),
    ]
