# Generated by Django 4.0.5 on 2022-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app_teacher', '0005_delete_a_rename_option1_question_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='quiz_app_teacher.question'),
        ),
    ]
